name: Allure Report Deployment

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        # Флаг --ignore-missing-args или обычный pip install pytest, если файла requirements.txt нет в корне
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install pytest selenium allure-pytest; fi

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Tests
        run: |
          pytest --alluredir=allure-results --headless
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true # Если ветки gh-pages еще нет, этот шаг просто пропустится, а не уронит сборку!
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report Action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
            allure_results: allure-results
            allure_history: allure-history
            keep_reports: 20

      - name: Create non-empty directory fallback
        if: always()
        run: |
              mkdir -p allure-history
                touch allure-history/.gitkeep

            - name: Deploy Allure Report to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              if: always()
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_branch: gh-pages
                publish_dir: allure-history