name: Allure Report Deployment

# Тесты запускаются автоматически ТОЛЬКО при пуше в мастер или вручную
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    # Даем серверу полные права на запись контента в репозиторий
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Tests
        run: |
          pytest --alluredir=allure-results --headless
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report Action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy Allure Report to GitHub Pages
        # Используем именно этот экшен, он идеально работает с contents: write
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history